Traceback (most recent call last):
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/jupyter_cache/executors/utils.py", line 58, in single_nb_execution
    executenb(
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1314, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/jupyter_core/utils/__init__.py", line 165, in wrapped
    return loop.run_until_complete(inner)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.12/lib/python3.12/asyncio/base_events.py", line 664, in run_until_complete
    return future.result()
           ^^^^^^^^^^^^^^^
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 709, in async_execute
    await self.async_execute_cell(
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 1062, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "/Users/seanwalsh/Documents/Github-Mac-Laptop/philstatsbook/.venv/lib/python3.12/site-packages/nbclient/client.py", line 918, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
my_prior = [.25, .25, .25, .25]

my_size_sample_space = 100
my_size_parameter_space = 4

my_observed_values = [50, 50, 50]

mean_1 = 50
mean_2 = 60
mean_3 = 70
var_1 = 10
var_2 = 30
var_3 = 30

my_likelihood = [[None]*4 for _ in range(4)]

my_likelihood[0] = [1/size_sample_space]*size_sample_space

std_dev_1 = np.sqrt(var_1)
std_dev_2 = np.sqrt(var_2)
std_dev_3 = np.sqrt(var_3)

my_min = min(mean_1 - 3*std_dev_1, mean_2 - 3*std_dev_2, mean_3 - 3*std_dev_3)
my_max = max(mean_1 + 3*std_dev_1, mean_2 + 3*std_dev_2, mean_3 + 3*std_dev_3)

my_sample_space_alt = np.linspace(my_min, my_max, size_sample_space)

my_likelihood[1] = norm.pdf(my_sample_space_alt, mean_1, std_dev_1)
my_likelihood[2] = norm.pdf(my_sample_space_alt, mean_2, std_dev_2)
my_likelihood[3] = norm.pdf(my_sample_space_alt, mean_3, std_dev_3)

bayes_simple(my_size_sample_space, my_size_parameter_space, my_prior, my_likelihood, my_observed_values)
------------------


[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
Cell [0;32mIn[4], line 17[0m
[1;32m     13[0m var_3 [38;5;241m=[39m [38;5;241m30[39m
[1;32m     15[0m my_likelihood [38;5;241m=[39m [[[38;5;28;01mNone[39;00m][38;5;241m*[39m[38;5;241m4[39m [38;5;28;01mfor[39;00m _ [38;5;129;01min[39;00m [38;5;28mrange[39m([38;5;241m4[39m)]
[0;32m---> 17[0m my_likelihood[[38;5;241m0[39m] [38;5;241m=[39m [[38;5;241m1[39m[38;5;241m/[39m[43msize_sample_space[49m][38;5;241m*[39msize_sample_space
[1;32m     19[0m std_dev_1 [38;5;241m=[39m np[38;5;241m.[39msqrt(var_1)
[1;32m     20[0m std_dev_2 [38;5;241m=[39m np[38;5;241m.[39msqrt(var_2)

[0;31mNameError[0m: name 'size_sample_space' is not defined

